### ISSUE TITLE
Assignment - Github Profile

### ISSUE THREAD

**Issue by arpit-dwivedi** [DevIncept/Prerequisite-OpenCV#1]
This issue is for submission of Assignment - Github Profile, just comment `Assignment-Github Profile Done` below if completed and tag @arpit-dwivedi .

**Comment by dheeraj24inferno** [comment]
Assignment-Github Profile done   @arpit-dwivedi

**Comment by sagarmittal1** [comment]
Assignment-Github Profile Done @arpit-dwivedi

**Comment by arpit-dwivedi** [comment]
@dheeraj24inferno @sagarmittal1 

Task completed!!!
Access to the new module will be given on Wednesday.

**Comment by tdvraju** [comment]
Assignment-Github Profile  Done @arpit-dwivedi

**Comment by sush-2012** [comment]
Assignment-Github Profile Done @arpit-dwivedi

**Comment by gurleen3** [comment]
Assignment-Github Profile Done @arpit-dwivedi

**Comment by samruddhid5** [comment]
Assignment-Github Profile Done @arpit-dwivedi

**Comment by SathvickN** [comment]
Assignment-Github Profile Done @arpit-dwivedi

**Comment by akshbswas98** [comment]
Assignment-Github Profile Done @akshbswas98

**Comment by abhap12** [comment]
Assignment-Github Profile Done @arpit-dwivedi
